name: min_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pip
  - python>=3.9
  - scikit-image
  - scipy
  - pip:
      - opencv-python-headless
      - pyoptflow
